# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: "latest"

      - name: Add pnpm package export globally
        run: pnpm add --global pnpm-lock-export

      - name: Generate package-lock.json file
        run: pnpm-lock-export --dest package-lock.json

      - name: Install Dependencies
        run: pnpm install

      - name: Run buil if present
        run: pnpm run build --if-present

      - name: Run tests if present
        run: pnpm run test  --if-present
